# Generated by Django 4.2.2 on 2023-06-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='appointmenttable',
        ),
        migrations.RenameModel(
            old_name='contact',
            new_name='contacttable',
        ),
    ]
