# Generated by Django 4.2.2 on 2023-06-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registrationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrationform',
            new_name='registrationtable',
        ),
    ]
