# Generated by Django 4.2.2 on 2023-07-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_password_registrationtable_passwords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminregistertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('ree_password', models.CharField(max_length=200)),
            ],
        ),
    ]
