# Generated by Django 4.2.2 on 2023-07-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_adminregistertable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationtable',
            old_name='email',
            new_name='emaill',
        ),
        migrations.RenameField(
            model_name='registrationtable',
            old_name='fname',
            new_name='finame',
        ),
        migrations.RenameField(
            model_name='registrationtable',
            old_name='lname',
            new_name='laname',
        ),
        migrations.RenameField(
            model_name='registrationtable',
            old_name='re_password',
            new_name='re_passwords',
        ),
    ]
